Repository gabygab159/foodPickupOrdering, pull requests merged in 2021-04, with the labels that each got.

#11 Add project brainstorm document
  project-brainstorm.md
Labels: documentation

#17 We made it Routes definition that requires a final review 90%
  behaviour-requirements.md
  docs/ERD_foodOrdering.drawio
  docs/behaviour-requirements.md
Labels: documentation

#18 Front end
  package-lock.json
  public/images/food-icon.png
  public/images/soup.png
  styles/layout.scss
  views/index-og.ejs
  views/index.ejs
  views/nav.ejs
Labels: frontend

#21 Refactor express server
  docs/behaviour-requirements.md
  lib/db.js
  lib/orders-queries.js
  lib/restaurants-queries.js
  lib/users-queries.js
  package-lock.json
  package.json
  routes/users-route.js
  routes/users.js
  server.js
Labels: backend

#22 Feature/twilio helper function
  helper-functions/twilio-test.js
  helper-functions/twilio.js
  package-lock.json
  package.json
Labels: backend

#28 Add menu-queries and menus-routes
  lib/menus-queries.js
  routes/menus-routes.js
Labels: backend

#34 Cleaning files
  docs/project-brainstorm.md
  helper-functions/twilio-test.js
  helper-functions/twilio.js
  lib/db.js
  lib/menus-queries.js
  lib/orders-queries.js
  lib/restaurants-queries.js
  lib/users-queries.js
  routes/menus-routes.js
  routes/users-routes.js
  routes/widgets.js
Labels: cleaning, documentation

#36 Fix users-routes reference
  server.js
Labels: bug-fix

#35 Front end Improvements
  public/styles/cart.css
  public/styles/menu-items.css
  views/cart.ejs
  views/index-og.ejs
  views/index.ejs
  views/messages.ejs
  views/nav.ejs
Labels: frontend

#39 Routes/menu items
  lib/menus-queries.js
  package-lock.json
  routes/menus-routes.js
  server.js
Labels: app-requirements

#42 026 implement messages routing
  db/schema/06_orders.sql
  helper-functions/messages.js
  lib/messages-queries.js
  routes/messages-routes.js
  server.js
Labels: backend

#43 Fix sql query for getMessagesById function
  lib/messages-queries.js
Labels: backend

#44 27 implement order items routing
  lib/order-items-queries.js
  routes/order-items-routes.js
  server.js
Labels: backend

#48 Use restaurant router
  package-lock.json
  package.json
  routes/restaurants-routes.js
  server.js
Labels: backend

#49 47 create ejs folder structure
  server.js
  views/index.ejs
  views/messages.ejs
  views/pages/index.ejs
  views/partials/cart.ejs
  views/partials/head.ejs
  views/partials/menu-items.ejs
  views/partials/messages.ejs
  views/partials/nav.ejs
Labels: frontend

#53 Orders routing
  lib/orders-queries.js
  routes/orders-routes.js
  views/partials/menu-items.ejs
Labels: backend

#55 menu scroll, fixed right side
  public/styles/cart.css
  public/styles/layout.css
  public/styles/menu-items.css
Labels: frontend

#56 Addneworder
  lib/orders-queries.js
  routes/orders-routes.js
Labels: app-requirements, backend

#61 Checkout queries
  helper-functions/twilio-test.js
  helper-functions/twilio.js
  lib/checkout_queries.js
  package-lock.json
  routes/checkout-routes.js
  server.js
Labels: backend

#64 58 refactor index route 2
  lib/orders-queries.js
  routes/index-routes.js
  views/partials/cart.ejs
  views/partials/messages.ejs
Labels: app-requirements, backend, frontend

#65 css changes
  db/seeds/05_menu_items.sql
  lib/checkout-queries.js
  public/styles/cart.css
  public/styles/layout.css
  public/styles/menu-items.css
  public/styles/nav.css
  views/partials/cart.ejs
  views/partials/head.ejs
  views/partials/messages.ejs
  views/partials/nav.ejs
Labels: frontend

#66 Fix bug to add items to an existing order
  routes/orders-routes.js
Labels: bug-fix

#71 add responsive
  lib/checkout_queries.js
  public/styles/cart.css
  public/styles/layout.css
  public/styles/layout.scss
Labels: frontend

#72 67 implement form on checkout button
  helper-functions/send-sms.js
  helper-functions/twilio-test.js
  lib/checkout_queries.js
  lib/orders-queries.js
  routes/checkout-routes.js
  routes/index-routes.js
  routes/orders-routes.js
  server.js
  views/partials/cart.ejs
  views/partials/messages.ejs
Labels: app-requirements, backend, frontend

#75 Clean routes
  routes/checkout-routes.js
  routes/index-routes.js
  routes/menus-routes.js
  routes/messages-routes.js
  routes/order-items-routes.js
  routes/orders-routes.js
  routes/restaurants-routes.js
  routes/users-routes.js
Labels: cleaning

#76 clean views folder and clean up css
  public/styles/cart.css
  public/styles/layout.scss
  public/styles/menu-items.css
  public/styles/nav.css
  routes/index-routes.js
  views/pages/index.ejs
  views/partials/cart.ejs
  views/partials/head.ejs
  views/partials/menu-items.ejs
  views/partials/messages-sam.ejs
  views/partials/messages.ejs
Labels: cleaning
